/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:85dfc026-144d-4c4c-af14-8d904eb3a05f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dmooRBeOF",
    "aws_user_pools_web_client_id": "303umag5ku5afrkoja12ul7q91",
    "oauth": {}
};


export default awsmobile;
